export type ServiceBrand = {
  slug: string
  name: string
  logoSrc: string
  logoAlt: string
  category: 'terminale' | 'drukarki' | 'skanery' | 'mixed'
  shortDesc: string
  products: string
  seriesList: Array<{ series: string; description: string; typicalDevices: string }>
  heroLead: string
  heroTitle: string
  heroDescription: string
  /** Opcjonalny obraz tła hero (dark theme). Jeśli brak — jasny hero z logo. */
  heroImage?: string
  /** Override wariantu cennika. Dla marek które mają np. drukarki + terminale
   *  (jak Honeywell) ustaw 'all'. Domyślnie wyliczane z category. */
  pricingVariant?: 'printers' | 'devices' | 'all'
  commonIssues: Array<{ title: string; description: string }>
  faqs: Array<{ q: string; a: string }>
  metaTitle: string
  metaDescription: string
}

export const serviceBrands: ServiceBrand[] = [
  {
    slug: 'honeywell',
    name: 'Honeywell',
    logoSrc: '/images/partners/logo_honeywell.png',
    logoAlt: 'Serwis urządzeń Honeywell i Intermec — drukarki, terminale, skanery',
    category: 'mixed',
    pricingVariant: 'all',
    shortDesc: 'Drukarki PM45/PM43, terminale CT/EDA, skanery Voyager',
    products: 'Drukarki Honeywell i Intermec (PM45, PM43, PX940, PD45), terminale CT/CK/EDA, skanery Voyager i Xenon',
    heroTitle: 'Serwis Honeywell i Intermec — drukarki, terminale, skanery',
    heroDescription: 'Pogwarancyjny serwis urządzeń Honeywell i Intermec: drukarki PM45/PX940/PD45 oraz legacy PM43/PM4i/PX4i/PX6i, terminale CT/CK/EDA, skanery Voyager i Xenon. Oryginalne części, wysyłka z całej Polski.',
    heroImage: '/images/serwis-hero/honeywell-hero.webp',
    heroLead: 'TAKMA serwisuje urządzenia Honeywell od ponad 20 lat — w tym starsze drukarki, terminale i skanery Intermec, przejęte przez Honeywell w 2013 roku i wciąż powszechnie używane w polskich magazynach. Naprawiamy pełny zakres urządzeń AutoID obu marek: drukarki etykiet (biurkowe, przemysłowe, mobilne), terminale mobilne oraz skanery kodów kreskowych. Pracujemy na oryginalnych częściach producenta — zachowujesz klasę IP65/IP67 i deklarowane parametry druku.',
    metaTitle: 'Serwis Honeywell i Intermec — drukarki, terminale | TAKMA',
    metaDescription: 'Pogwarancyjny serwis Honeywell/Intermec: drukarki PM45, PM43, PX940, PD45, terminale CT40, EDA51, skanery Voyager, Xenon. Diagnostyka 48h — TAKMA Wrocław.',
    seriesList: [
      { series: 'Drukarki przemysłowe Honeywell', description: 'Nowa generacja drukarek termotransferowych 4" — PM45, PM45c (kompaktowa), PX45 (elastyczna) oraz PX940 z wbudowaną weryfikacją nadruku etykiety. Rozdzielczości 203/300/600 dpi. Do produkcji, magazynu, logistyki 3PL.', typicalDevices: 'PM45, PM45c, PX45, PX45A, PX940, PX940V' },
      { series: 'Drukarki biurkowe Honeywell', description: 'Kompaktowe drukarki biurkowe — PD45, PD45s (z wyświetlaczem), PC42, PC42d, PC42t. Do retailu, logistyki, healthcare, administracji.', typicalDevices: 'PD45, PD45S, PC42, PC42d, PC42t, PC23d' },
      { series: 'Drukarki Intermec (legacy)', description: 'Starsze drukarki Intermec (przejęte przez Honeywell w 2013 r.) wciąż używane w produkcji i magazynach — TAKMA serwisuje pełny zakres. Obsługujemy języki IPL, DP, ZPL, Fingerprint.', typicalDevices: 'PM43, PM43c, PM4i, PX4i, PX6i, PD43, PD41, PC43d, PC43t, PF4i, PF2i' },
      { series: 'Drukarki mobilne', description: 'Przenośne drukarki z baterią do serwisu w terenie, logistyki kurierskiej, inwentaryzacji — Honeywell RP2, RP2f, RP4, RP4f oraz legacy Intermec PR2, PR3, PB32, PB42, PB50, PB51.', typicalDevices: 'RP2, RP2f, RP4, RP4f, PR2, PR3, PB32, PB42, PB50, PB51' },
      { series: 'Terminale CT Series', description: 'Mobilne terminale do magazynu i logistyki — CT40, CT45, CT47, CT60, CT70 XP. Android Enterprise, skaner 2D, Wi-Fi 6.', typicalDevices: 'CT40, CT40 XP, CT45, CT47, CT60, CT60 XP, CT70' },
      { series: 'Terminale CK Series', description: 'Wytrzymałe terminale rugged z klawiaturą — CK65, CK75. Klasa IP65/IP67, temperatura -20°C.', typicalDevices: 'CK65, CK75, CK3X, CK3R' },
      { series: 'Terminale EDA Series', description: 'Terminale klasy enterprise — EDA51, EDA52, EDA71. Ekran 5-6 cali, skaner 2D, Android 11/13.', typicalDevices: 'EDA51, EDA52, EDA61K, EDA71' },
      { series: 'Skanery Voyager', description: 'Ręczne skanery 1D/2D do handlu i logistyki — Voyager 1200g, 1250g, 1452g (BT), 1602g.', typicalDevices: 'Voyager 1200g, 1250g, 1350g, 1452g, 1602g' },
      { series: 'Skanery Xenon', description: 'Wysokiej klasy skanery 2D imager — Xenon 1900, 1902g, 1950g, 1952g. Kody 2D z wyświetlaczy, DPM, UDI.', typicalDevices: 'Xenon 1900, 1902, 1950, 1950g-HD, 1952, Xenon XP' },
    ],
    commonIssues: [
      { title: 'PM45 / PM43 — pionowe białe pasy na wydruku etykiety', description: 'Wypalone punkty termiczne na głowicy drukującej (thermal burnline damage) — częsty problem po 30+ km druku. Wymiana oryginalnej głowicy Honeywell 203/300/600 dpi + kalibracja ciśnienia i temperatury. Dotyczy też legacy PM4i, PX4i, PX6i.' },
      { title: 'Intermec PM4i / PX6i — drukarka nie komunikuje się z hostem', description: 'Uszkodzony moduł Ethernet/Serial lub konflikty starszych języków IPL/Fingerprint. Diagnoza portu, reflashing firmware na odpowiednią wersję, ewentualnie wymiana karty sieciowej lub głównej płyty.' },
      { title: 'PD45 / PC43 — drukarka wyrzuca "Media Out" mimo założonych etykiet', description: 'Rozkalibrowany czujnik przerw (gap sensor) lub zabrudzone okienko czujnika. Kalibracja + czyszczenie, w razie potrzeby wymiana czujnika transmisyjnego lub refleksyjnego.' },
      { title: 'Terminal CT40/EDA51 nie ładuje baterii', description: 'Najczęściej przyczyną jest uszkodzenie złącza USB-C lub pogięcie pinów w stacji dokującej. Sprawdzamy rezystancję złącza, przelutowujemy kabel zasilający i testujemy pod obciążeniem.' },
      { title: 'Skaner Voyager/Xenon nie czyta kodów 2D', description: 'W skanerach imagerowych (Xenon 1900/1950) zablokowany imager lub zabrudzona optyka. Czyszczenie modułu, reset firmware i kontrola temperatury pracy LED.' },
      { title: 'Ekran CT40/EDA51 pęknięty lub bez dotyku', description: 'Wymiana LCD + digitizera z zachowaniem szczelności IP65/IP67. Używamy oryginalnych paneli Honeywell — naprawa w 5–7 dni.' },
      { title: 'Terminal CK65 nie łączy się z siecią Wi-Fi', description: 'Problem z modułem radiowym (antena, układ) albo konfiguracja profilu. Test kalibracji WLAN, aktualizacja sterowników, ewentualna wymiana modułu.' },
      { title: 'Klawisze w CK65/CK75 nie reagują', description: 'Zużycie mat silikonowych lub uszkodzenie taśmy flex. Wymiana klawiatury + matek silikonowych z gwarancją 3 miesiące.' },
      { title: 'Skaner Voyager 1250g tylko piknie, nie transmituje', description: 'Zwykle sufiks CR/LF nie jest ustawiony albo kabel USB utracił transmisję danych. Diagnoza + kod konfiguracyjny lub wymiana kabla.' },
    ],
    faqs: [
      { q: 'Czy TAKMA jest autoryzowanym serwisem Honeywell?', a: 'Jesteśmy niezależnym, profesjonalnym serwisem pogwarancyjnym urządzeń Honeywell. Pracujemy na oryginalnych częściach Honeywell, stosujemy certyfikowane procedury i dbamy o zachowanie klasy IP65/IP67 po każdej naprawie. Dla napraw gwarancyjnych urządzeń Honeywell kierujemy klientów bezpośrednio do producenta.' },
      { q: 'Czy naprawiacie starsze drukarki Intermec (PM43, PM4i, PX4i, PX6i, PD43)?', a: 'Tak. Naprawiamy pełen zakres drukarek Intermec — od przemysłowych PM43, PM43c, PM4i, PX4i, PX6i i desktopowych PD41, PD43, PC43d, PC43t po mobilne PB32, PB42, PB50, PB51, PR2 i PR3. Po przejęciu Intermec przez Honeywell w 2013 roku wszystkie te modele są wspierane serwisowo. Wymieniamy głowice, wałki, płyty główne, moduły sieciowe. Części do starszych modeli z czasem dostawy 7–14 dni, ale pełen zakres napraw realizujemy.' },
      { q: 'Ile kosztuje wymiana głowicy w Honeywell PM45 / PM43?', a: 'Wymiana głowicy w drukarkach przemysłowych Honeywell (PM45, PM45c, PX45, PX940) oraz legacy Intermec (PM43, PM4i, PX4i, PX6i) od 1 600 PLN netto za serwis. Koszt samej głowicy 1 100–2 400 PLN netto zależnie od modelu i rozdzielczości (203/300/600 dpi). Dla drukarek biurkowych (PD45, PD45s, PD43, PC42/PC43) wymiana głowicy od 430 PLN netto.' },
      { q: 'Ile kosztuje naprawa terminala Honeywell CT40/EDA51?', a: 'Diagnostyka jest darmowa przy zleceniu naprawy. Orientacyjne ceny: wymiana ekranu (LCD + digitizer) od 350 PLN netto, wymiana baterii od 120 PLN netto, naprawa złącza ładowania od 250 PLN netto, wymiana obudowy od 180 PLN netto. Dokładna wycena po diagnozie.' },
      { q: 'Czy naprawiacie skanery Honeywell Voyager i Xenon po gwarancji?', a: 'Tak. Naprawiamy wszystkie skanery Honeywell — Voyager 1200g/1250g/1452g/1602g oraz Xenon 1900/1902/1950/1952. Typowe naprawy: wymiana modułu imager, naprawa elektroniki, wymiana kabli i przełączników.' },
      { q: 'Jak długo trwa naprawa urządzenia Honeywell / Intermec?', a: 'Diagnostyka w 48h od dostarczenia. Naprawa zwykle 5–7 dni roboczych dla aktualnych modeli (zależy od dostępności części). Dla najpopularniejszych modeli (CT40, EDA51, PM45) mamy części na stanie — naprawa ekspresowa 48h. Dla legacy Intermec (PM4i, PX6i, PB32/42/50) czas naprawy 7–14 dni ze względu na specjalne części.' },
      { q: 'Czy mogę wysłać urządzenie Honeywell do TAKMA z Warszawy/Krakowa?', a: 'Tak, obsługujemy klientów z całej Polski. Możesz zamówić kuriera przez nasz formularz (odbiór w 24h) lub wysłać samodzielnie na adres: TAKMA, ul. Poświęcka 1a, 51-128 Wrocław. Przy naprawach powyżej 200 PLN netto odsyłka na nasz koszt.' },
    ],
  },
  {
    slug: 'datalogic',
    name: 'Datalogic',
    logoSrc: '/images/partners/logo_datalogic.png',
    logoAlt: 'Serwis terminali i skanerów Datalogic',
    category: 'mixed',
    shortDesc: 'Memor, Skorpio, Joya Touch, skanery Gryphon',
    products: 'Memor, Skorpio, Joya Touch, skanery Gryphon',
    heroTitle: 'Serwis Datalogic — naprawa terminali i skanerów',
    heroDescription: 'Pogwarancyjny serwis urządzeń Datalogic: terminale mobilne Memor 1/10/20/30, Skorpio X5, Joya Touch, skanery Gryphon, QuickScan, PowerScan. Oryginalne części, wysyłka z całej Polski.',
    heroImage: '/images/serwis-hero/datalogic-hero.webp',
    heroLead: 'TAKMA serwisuje urządzenia Datalogic od ponad 15 lat — naprawiamy terminale mobilne Memor (Memor 1, Memor 10, Memor 20, Memor 30, Memor 35), Skorpio X5, Joya Touch oraz skanery ręczne Gryphon (GBT/GD/GM), QuickScan, PowerScan 9501/M9501. Specjalizujemy się w wymianie ekranów LCD + digitizer z zachowaniem szczelności IP65 oraz w diagnostyce modułów imager Omnidirectional 2D.',
    metaTitle: 'Serwis Datalogic — naprawa Memor, Skorpio, Gryphon | TAKMA',
    metaDescription: 'Pogwarancyjny serwis Datalogic: Memor 10/20/30, Skorpio X5, Joya Touch, skanery Gryphon GBT/GD. Darmowa diagnostyka 48h. Wysyłka z całej Polski — TAKMA Wrocław.',
    seriesList: [
      { series: 'Memor Series', description: 'Terminale mobilne Android — Memor 1, Memor 10, Memor 20, Memor 30, Memor 35. Ekran 5-6", skaner 2D, Wi-Fi ac/ax.', typicalDevices: 'Memor 1, Memor 10, Memor 20, Memor 30, Memor 35' },
      { series: 'Skorpio', description: 'Terminale rugged z klawiaturą — Skorpio X5. Klasa IP65, zakres temperatur od -20°C do 50°C. Do magazynu, chłodni, produkcji.', typicalDevices: 'Skorpio X5, Skorpio X4 (starsze)' },
      { series: 'Joya Touch', description: 'Terminale retailowe — Joya Touch 22, Joya Touch A6. Ekran 4,3", ergonomia sklepowa, doskonałe do stocktaking.', typicalDevices: 'Joya Touch 22, Joya Touch A6' },
      { series: 'Skanery Gryphon', description: 'Ręczne skanery 2D — Gryphon GBT (BT), GD (kabel), GM (wireless). Kody 1D/2D, DPM (oil-marking).', typicalDevices: 'Gryphon GBT4500, GD4500, GM4500, GBT4100, GD4100' },
      { series: 'QuickScan / PowerScan', description: 'Entry-level (QuickScan QBT2500, QD2500) i industrial (PowerScan 9501/M9501). Rugged do produkcji.', typicalDevices: 'QuickScan QBT2500, QD2500, PowerScan 9501, PowerScan M9501' },
    ],
    commonIssues: [
      { title: 'Memor 10/20 — ekran nie reaguje na dotyk', description: 'Digitizer uszkodzony po upadku lub temperaturze. Wymiana panelu LCD + digitizer z testem szczelności IP65. Naprawa 5–7 dni.' },
      { title: 'Skorpio X5 — błąd "Scan engine error"', description: 'Uszkodzony moduł imager albo zabrudzona optyka. Czyszczenie + reset firmware lub wymiana modułu skanującego.' },
      { title: 'Gryphon GBT4500 — nie łączy się z cradle BT', description: 'Problem pairing BT lub rozładowana bateria cradle. Diagnostyka modułu BT, reset pair, ewentualna wymiana baterii.' },
      { title: 'Joya Touch 22 — nie ładuje się w cradle', description: 'Zużyte piny pogo w cradle lub złącze terminala. Czyszczenie, pomiar rezystancji, wymiana pinów pogo w dock.' },
      { title: 'Memor 30/35 — "boot loop"', description: 'Problem firmware lub uszkodzona pamięć flash. Reflashing firmware, weryfikacja partycji, ewentualna wymiana płyty głównej.' },
      { title: 'PowerScan 9501 — nie czyta kodów 2D', description: 'Uszkodzony imager po uderzeniu (rugged ale ma limity). Wymiana modułu imager + kalibracja.' },
    ],
    faqs: [
      { q: 'Czy TAKMA jest autoryzowanym serwisem Datalogic?', a: 'Jesteśmy niezależnym serwisem pogwarancyjnym Datalogic — pracujemy na oryginalnych częściach Datalogic i stosujemy certyfikowane procedury naprawy. Dla napraw gwarancyjnych kierujemy klientów do dystrybucji Datalogic.' },
      { q: 'Ile kosztuje wymiana ekranu w Datalogic Memor 10?', a: 'Wymiana ekranu LCD + digitizer w Memor 10/20/30 od 350 PLN netto (bez kosztu ekranu — 450–650 PLN netto zależnie od modelu). Darmowa diagnostyka przy zleceniu naprawy.' },
      { q: 'Czy naprawiacie skanery Datalogic Gryphon i PowerScan?', a: 'Tak — cała rodzina skanerów Datalogic: Gryphon (GBT, GD, GM), QuickScan (QBT, QD), PowerScan (9501, M9501, PM9501). Wymiana modułów imager, płyt głównych, baterii skanerów BT.' },
      { q: 'Jak długo trwa naprawa Datalogic Skorpio X5?', a: 'Diagnostyka w 48h od dostarczenia, naprawa 5–7 dni roboczych. Dla Skorpio X5 mamy na stanie kluczowe części (klawiatura, ekran, moduł skanujący) — większość napraw realizujemy w 5 dni.' },
      { q: 'Czy wymieniacie baterie w terminalach Datalogic?', a: 'Tak. Wymieniamy baterie we wszystkich terminalach Datalogic — Memor, Skorpio, Joya Touch. Używamy oryginalnych baterii Datalogic (nie kompatybilnych "zamienników") — od 120 PLN netto za sam serwis + koszt baterii wg modelu.' },
    ],
  },
  {
    slug: 'm3-mobile',
    name: 'M3 Mobile',
    logoSrc: '/images/partners/logo_m3mobile.png',
    logoAlt: 'Serwis terminali M3 Mobile',
    category: 'terminale',
    shortDesc: 'Terminale UL20, SM20, SL10',
    products: 'Terminale UL20, SM20, SL10',
    heroTitle: 'Serwis M3 Mobile — naprawa terminali przemysłowych',
    heroDescription: 'Pogwarancyjny serwis terminali M3 Mobile: UL20, SM20, SM25, SL10, SL20. Wymiana ekranów, baterii, modułów skanujących. Oryginalne części, wysyłka z całej Polski.',
    heroImage: '/images/serwis-hero/m3-mobile-hero.webp',
    heroLead: 'M3 Mobile to koreański producent terminali rugged, który zyskuje w Polsce coraz większą popularność jako alternatywa dla Zebra i Honeywell. TAKMA serwisuje terminale M3 Mobile z rodzin UL20 (ultra-rugged), SM20/SM25 (smart mobile), SL10/SL20 (slim compact) — wymieniamy ekrany, baterie, moduły skanujące oraz prowadzimy kalibrację i aktualizacje firmware.',
    metaTitle: 'Serwis M3 Mobile — naprawa terminali UL20, SM20, SL10 | TAKMA',
    metaDescription: 'Pogwarancyjny serwis M3 Mobile: UL20, SM20, SM25, SL10, SL20. Wymiana ekranu, baterii, modułu skanującego. Darmowa diagnostyka 48h — TAKMA Wrocław, cała Polska.',
    seriesList: [
      { series: 'UL Series', description: 'Ultra-rugged terminale — UL20, UL20W, UL20X, UL20F (full keyboard). Najwyższa klasa wytrzymałości, MIL-STD-810G.', typicalDevices: 'UL20, UL20W, UL20X, UL20F' },
      { series: 'SM Series', description: 'Smart Mobile terminale — SM10, SM15, SM20, SM25. Ekran 5-6", Android Enterprise, idealne do retailu i magazynu.', typicalDevices: 'SM10, SM15, SM20, SM25' },
      { series: 'SL Series', description: 'Slim compact terminale — SL10, SL10H (high-end), SL20. Lżejsze, kompaktowe, do użytku w polu i handlu.', typicalDevices: 'SL10, SL10H, SL20' },
    ],
    commonIssues: [
      { title: 'UL20/UL20X nie ładuje baterii', description: 'Zużyte piny pogo w stacji dokującej lub uszkodzenie złącza ładującego w urządzeniu. Wymiana pinów pogo w cradle lub naprawa portu w terminalu.' },
      { title: 'SM20/SM25 — pęknięty ekran LCD', description: 'Wymiana całego modułu LCD + digitizer z przywróceniem szczelności IP67. Używamy oryginalnych paneli M3 Mobile. Naprawa 5–7 dni.' },
      { title: 'UL20 — skaner 2D nie czyta kodów', description: 'Imager zabrudzony lub uszkodzony po upadku. Czyszczenie modułu + kalibracja, w razie potrzeby wymiana modułu imager 2D na oryginalną część.' },
      { title: 'SL10/SL20 — terminal nie włącza się', description: 'Najczęściej rozładowana bateria pozostawiona na długo bez ładowania (deep discharge). Regeneracja baterii + diagnostyka płyty głównej.' },
      { title: 'SM20 — moduł Wi-Fi odłącza się od sieci', description: 'Problem z firmware lub uszkodzonym modułem WLAN. Aktualizacja firmware M3 Mobile, diagnoza anteny, ewentualna wymiana modułu radiowego.' },
    ],
    faqs: [
      { q: 'Czy TAKMA współpracuje z dystrybutorem M3 Mobile w Polsce?', a: 'Tak. Mamy dostęp do oryginalnych części M3 Mobile (ekrany, baterie, moduły skanujące) przez oficjalnych dystrybutorów producenta. Dzięki temu realizujemy naprawy szybko i zgodnie ze standardami M3 Mobile.' },
      { q: 'Ile kosztuje wymiana ekranu w M3 Mobile SM20?', a: 'Serwis wymiany ekranu (LCD + digitizer) od 350 PLN netto. Koszt samego ekranu 550–750 PLN netto zależnie od modelu (UL20, SM20, SL10). Darmowa diagnostyka przy zleceniu naprawy.' },
      { q: 'Jak długo trwa naprawa M3 Mobile UL20?', a: 'Diagnostyka w 48h od dostarczenia, naprawa zwykle 5–7 dni roboczych. Czas zależy od dostępności konkretnej części — dla UL20/SM20 najczęstsze części mamy na stanie.' },
      { q: 'Czy naprawiacie M3 Mobile starsze modele (UL20W, SM10)?', a: 'Tak, naprawiamy również starsze serie M3 Mobile (UL20W, SM10, SM15). Części do starszych modeli dostępne są z większym czasem oczekiwania (7–10 dni), ale pełen zakres napraw jest wykonywany.' },
      { q: 'Czy udzielacie gwarancji na naprawione terminale M3 Mobile?', a: 'Tak. Gwarancja na naprawę wynosi od 3 do 6 miesięcy — zależnie od rodzaju naprawy i wymienionej części. Dokument gwarancyjny jest załączany do odsyłanego urządzenia wraz z listą wykonanych prac.' },
    ],
  },
  {
    slug: 'newland',
    name: 'Newland',
    logoSrc: '/images/partners/logo_newland.png',
    logoAlt: 'Serwis skanerów i terminali Newland',
    category: 'mixed',
    shortDesc: 'Skanery HR, MT90, terminale NFT10',
    products: 'Skanery HR, MT90, terminale NFT10',
    heroTitle: 'Serwis Newland — naprawa skanerów i terminali',
    heroDescription: 'Pogwarancyjny serwis urządzeń Newland: skanery ręczne HR, MT90, terminale mobilne NFT10, MT65, MT95. Oryginalne części, wysyłka z całej Polski, diagnostyka 48h.',
    heroImage: '/images/serwis-hero/newland-hero.webp',
    heroLead: 'Newland to chiński producent urządzeń AutoID, który w ostatnich latach zyskuje popularność dzięki bardzo dobremu stosunkowi ceny do jakości. TAKMA serwisuje skanery ręczne Newland (HR, MT90, NLS-HR serii), terminale mobilne (NFT10, MT65, MT95) oraz stacjonarne skanery FM (FM100, FM430). Używamy oryginalnych części Newland i stosujemy procedury naprawy zgodne z dokumentacją producenta.',
    metaTitle: 'Serwis Newland — naprawa HR22, MT90, NFT10 | TAKMA',
    metaDescription: 'Pogwarancyjny serwis Newland: skanery HR, MT90, NLS, terminale NFT10, MT65, MT95. Darmowa diagnostyka 48h. Oryginalne części — TAKMA Wrocław, cała Polska.',
    seriesList: [
      { series: 'Skanery HR', description: 'Ręczne skanery 2D serii HR — HR11, HR15, HR22, HR32. Czytają kody 1D/2D, dostępne przewodowe i BT.', typicalDevices: 'HR11, HR15, HR22, HR22 Plus, HR32' },
      { series: 'Skanery MT90', description: 'MT90 Orca — małe, rugged skanery magazynowe z Wi-Fi/BT. Idealne do inwentaryzacji i cross-docking.', typicalDevices: 'MT90, MT90B, MT90L (LoRa)' },
      { series: 'Terminale NFT10', description: 'NFT10 Pilot — lekkie terminale Android do małych punktów handlowych i logistyki. Ekran 4", skaner 2D.', typicalDevices: 'NFT10, NFT10 Pilot, NFT10 Pilot Pro' },
      { series: 'Terminale MT65 / MT95', description: 'Rugged terminale mobilne — MT65, MT95. Ekran 5-6", Android 11+, skaner 2D, Wi-Fi 6.', typicalDevices: 'MT65, MT95, MT90 Orca' },
      { series: 'Skanery stacjonarne FM', description: 'Stacjonarne skanery FM — FM100, FM430, FM5080. Do kas, stanowisk logistycznych, POS.', typicalDevices: 'FM100, FM430, FM5080' },
    ],
    commonIssues: [
      { title: 'Newland HR22/HR32 — skaner nie odczytuje kodów 2D', description: 'Zabrudzona optyka lub uszkodzony imager. Czyszczenie + kalibracja. Dla uszkodzonego modułu — wymiana imagera.' },
      { title: 'MT90 Orca — nie łączy się z siecią Wi-Fi', description: 'Problem z profilem WLAN lub antena wewnętrzna. Reset konfiguracji, diagnoza anteny, ewentualna wymiana modułu radiowego.' },
      { title: 'NFT10 — ekran pęknięty lub brak dotyku', description: 'Wymiana LCD + digitizer z zachowaniem szczelności IP65. Oryginalne panele Newland, naprawa 5–7 dni.' },
      { title: 'HR11/HR15 — kabel USB bez transmisji danych', description: 'Przewód uszkodzony mechanicznie (najczęstsza usterka skanerów kablowych). Wymiana kabla USB z oryginalnym złączem RJ.' },
      { title: 'MT65/MT95 — bateria rozładowuje się w mniej niż 2 h', description: 'Zużyta bateria po 2–3 latach pracy. Regeneracja lub wymiana baterii. Oryginalne baterie Newland z gwarancją 3 miesięcy.' },
    ],
    faqs: [
      { q: 'Czy naprawiacie wszystkie skanery Newland?', a: 'Tak. Naprawiamy skanery ręczne (HR, MT90, NLS-HR), stacjonarne (FM100, FM430, FM5080) i wbudowane (OEM). Największe doświadczenie mamy z rodziną HR (HR11, HR15, HR22, HR32) — to najpopularniejsze skanery Newland w Polsce.' },
      { q: 'Ile kosztuje naprawa skanera Newland HR22?', a: 'Diagnostyka jest darmowa przy zleceniu naprawy. Typowe naprawy: wymiana kabla USB od 80 PLN netto, czyszczenie/kalibracja imagera od 120 PLN netto, wymiana modułu imager od 350 PLN netto. Dokładna wycena po diagnozie.' },
      { q: 'Czy macie części do Newland MT90 Orca?', a: 'Tak. Do MT90 mamy na stanie baterie, moduły skanujące i wałki ochronne. Dla ekranu LCD czas dostawy 5–7 dni. Pełen zakres napraw MT90 i MT90B realizujemy.' },
      { q: 'Jak długo trwa naprawa Newland NFT10?', a: 'Diagnostyka w 48h od dostarczenia, naprawa zwykle 5–7 dni roboczych. NFT10 to relatywnie nowy model — części dostępne z 3–5 dniowym czasem sprowadzenia. Ekspresowa naprawa 48h dla kluczowych usterek.' },
      { q: 'Czy naprawiacie skanery OEM Newland wbudowane w kioski?', a: 'Tak — naprawiamy skanery OEM Newland (serie NLS, EM) wbudowane w kioski samoobsługowe, maszyny vendingowe, stacje POS. Wymagamy dostarczenia modułu — nie świadczymy serwisu u klienta w tej kategorii.' },
    ],
  },
  {
    slug: 'citizen',
    name: 'Citizen',
    logoSrc: '/images/partners/logo_citizen.png',
    logoAlt: 'Serwis drukarek etykiet Citizen',
    category: 'drukarki',
    shortDesc: 'Drukarki CL-S, CL-E, CT-S',
    products: 'Drukarki CL-S, CL-E, CT-S',
    heroTitle: 'Serwis Citizen — naprawa drukarek etykiet i paragonowych',
    heroDescription: 'Pogwarancyjny serwis drukarek Citizen: CL-S, CL-E (etykietowe termotransferowe) oraz CT-S (termiczne paragonowe). Wymiana głowic, wałków, zasilaczy. Oryginalne części.',
    heroImage: '/images/serwis-hero/citizen-hero.webp',
    heroLead: 'Citizen to japoński producent wysokiej klasy drukarek etykiet i paragonów, cenionych za niezawodność i jakość druku. TAKMA serwisuje drukarki etykiet Citizen CL-S (CL-S521, CL-S621, CL-S6621) i CL-E (CL-E300, CL-E321, CL-E331) oraz drukarki paragonowe termiczne CT-S (CT-S310, CT-S801, CT-S851, CT-S4500). Wymieniamy głowice drukujące, wałki dociskowe, zasilacze i płyty główne — zawsze na oryginalnych częściach Citizen.',
    metaTitle: 'Serwis Citizen — naprawa drukarek CL-S, CL-E, CT-S | TAKMA',
    metaDescription: 'Pogwarancyjny serwis drukarek Citizen: CL-S521, CL-S621, CL-E321, CT-S310, CT-S801. Wymiana głowic, wałków, płyt głównych. Darmowa diagnostyka — TAKMA Wrocław.',
    seriesList: [
      { series: 'CL-S Series', description: 'Biurkowe drukarki etykiet termotransferowe — CL-S521, CL-S621, CL-S631, CL-S6621. Rozdzielczość 203/300 dpi, Ethernet + USB.', typicalDevices: 'CL-S521, CL-S621, CL-S631, CL-S6621, CL-S700' },
      { series: 'CL-E Series', description: 'Kompaktowe drukarki etykiet — CL-E300, CL-E321, CL-E331, CL-E730. Intuicyjny panel LCD, mniejsze gabaryty niż CL-S.', typicalDevices: 'CL-E300, CL-E321, CL-E331, CL-E720, CL-E730' },
      { series: 'CT-S Series (POS)', description: 'Drukarki paragonowe termiczne — CT-S310, CT-S801, CT-S851, CT-S4500. Do restauracji, sklepów, POS.', typicalDevices: 'CT-S310, CT-S601, CT-S801, CT-S851, CT-S4500' },
    ],
    commonIssues: [
      { title: 'Citizen CL-S521 — białe pasy na wydruku', description: 'Wypalone punkty na głowicy drukującej. Wymiana głowicy 203 lub 300 dpi, kalibracja ciśnienia docisku. Oryginalne głowice Citizen.' },
      { title: 'CL-E321 — drukarka "ciągnie" papier i przepuszcza etykiety', description: 'Rozkalibrowany czujnik przerw (gap sensor) lub zabrudzone okienko czujnika. Kalibracja + czyszczenie, ewentualna wymiana czujnika.' },
      { title: 'CT-S310/CT-S801 — rwie papier termiczny', description: 'Zużyty wałek dociskowy (platen roller) lub uszkodzony obcinak automatyczny. Wymiana wałka + kalibracja pozycji cięcia.' },
      { title: 'CL-S621 — "Paper Out" mimo założonego nośnika', description: 'Zabrudzony lub rozkalibrowany czujnik transmisyjny. Kalibracja, czyszczenie lub wymiana czujnika.' },
      { title: 'CT-S851 — zielona dioda miga, nie drukuje', description: 'Status error — problem firmware, uszkodzona pamięć lub komunikacja z hostem. Reflashing firmware, diagnostyka portu USB/Serial/Ethernet.' },
    ],
    faqs: [
      { q: 'Ile kosztuje wymiana głowicy w Citizen CL-S521?', a: 'Wymiana głowicy drukującej 203 dpi w CL-S521/CL-S621 od 430 PLN netto (serwis). Koszt samej głowicy 350–600 PLN netto zależnie od modelu. Dla głowic 300 dpi ceny nieco wyższe. Darmowa diagnostyka przy zleceniu.' },
      { q: 'Czy naprawiacie drukarki paragonowe Citizen CT-S?', a: 'Tak. Pełen zakres napraw CT-S310, CT-S601, CT-S801, CT-S851, CT-S4500. Najczęstsze usterki: wymiana głowicy termicznej, wałka, obcinaka automatycznego, płyty głównej.' },
      { q: 'Jak długo trwa naprawa Citizen CL-S521?', a: 'Diagnostyka w 48h od dostarczenia, naprawa zwykle 5 dni roboczych. Oryginalne głowice i wałki Citizen mamy na stanie lub zamawiamy z dostawą 3–5 dni.' },
      { q: 'Czy Citizen CL-S wymaga oryginalnych materiałów eksploatacyjnych?', a: 'Drukarki Citizen działają z większością standardowych etykiet i taśm TT/WR (woskowych, wosk-żywica, żywicznych) — nie ma chipowania jak w niektórych innych markach. Używanie taniej jakości materiałów może jednak przyspieszyć zużycie głowicy.' },
      { q: 'Dajecie gwarancję na naprawy Citizen?', a: 'Tak — 3 miesiące na serwis elektroniki/mechaniki, 3 miesiące na wymienioną głowicę drukującą. Pisemna gwarancja jest załączana do każdego zlecenia. Dla wałków dociskowych i części eksploatacyjnych gwarancja producenta.' },
    ],
  },
  {
    slug: 'godex',
    name: 'Godex',
    logoSrc: '/images/partners/logo-godex.png',
    logoAlt: 'Serwis drukarek etykiet Godex',
    category: 'drukarki',
    shortDesc: 'Drukarki G500, EZ, RT700',
    products: 'Drukarki G500, EZ, RT700',
    heroTitle: 'Serwis Godex — naprawa drukarek etykiet',
    heroDescription: 'Pogwarancyjny serwis drukarek Godex: G500, EZ1100, EZ2250i, RT700, RT860i. Wymiana głowic, wałków, płyt głównych. Oryginalne części, wysyłka z całej Polski.',
    heroImage: '/images/serwis-hero/godex-hero.webp',
    heroLead: 'Godex to tajwański producent drukarek etykiet, popularny w Polsce dzięki dobrym parametrom za rozsądną cenę — szczególnie w segmencie SMB i logistyki 3PL. TAKMA serwisuje drukarki Godex z linii G (G500, G530), EZ (EZ1100 Plus, EZ1200 Plus, EZ2250i, EZ6200 Plus), RT (RT700, RT730, RT730x, RT860i) oraz większe przemysłowe ZX i EZ6000. Wymieniamy głowice drukujące, wałki, płyty główne, zasilacze i prowadzimy pełną kalibrację.',
    metaTitle: 'Serwis Godex — naprawa drukarek G500, EZ, RT700 | TAKMA',
    metaDescription: 'Pogwarancyjny serwis drukarek Godex: G500, EZ1100, EZ2250i, RT700, RT730, RT860i. Wymiana głowic, wałków, płyt głównych — TAKMA Wrocław, cała Polska.',
    seriesList: [
      { series: 'G Series', description: 'Podstawowe biurkowe drukarki etykiet — G500, G530. Rozdzielczość 203/300 dpi, USB + Serial, idealne do małych sklepów i biur.', typicalDevices: 'G500, G500 U, G530' },
      { series: 'EZ Series', description: 'Linia średnia i zaawansowana — EZ1100 Plus, EZ1200 Plus, EZ2250i, EZ6200 Plus. Ekran LCD, więcej interfejsów, szybszy druk.', typicalDevices: 'EZ1100 Plus, EZ1200 Plus, EZ2250i, EZ2350i, EZ6200 Plus' },
      { series: 'RT Series', description: 'Zaawansowane biurkowe z LCD — RT700, RT730, RT730x, RT860i. Wysoka jakość druku, Ethernet, BT.', typicalDevices: 'RT700, RT700i, RT730, RT730x, RT860i' },
      { series: 'ZX / EZ6000 przemysłowe', description: 'Drukarki przemysłowe 4" i 6" — ZX1200i, ZX1300i, EZ6000. Do pracy ciągłej, większe wolumeny.', typicalDevices: 'ZX1200i, ZX1300i, ZX430i, EZ6000' },
    ],
    commonIssues: [
      { title: 'Godex G500/G530 — białe pasy na wydruku', description: 'Wypalone punkty na głowicy drukującej. Wymiana głowicy 203/300 dpi. Oryginalne głowice Godex, gwarancja 3 miesiące.' },
      { title: 'EZ1100 Plus / EZ2250i — drukarka się przegrzewa i wyłącza', description: 'Uszkodzony zasilacz lub zablokowany wentylator. Wymiana zasilacza, czyszczenie wentylatora, aktualizacja firmware.' },
      { title: 'RT700/RT730 — "Head Open" mimo zamkniętej pokrywy', description: 'Rozkalibrowany czujnik pokrywy lub uszkodzona sprężyna blokady. Regulacja mechanizmu, wymiana czujnika.' },
      { title: 'G500 — nie ciągnie taśmy termotransferowej', description: 'Zużyte sprzęgło nawijaka taśmy lub uszkodzony silnik. Diagnoza mechaniki nawijaka, wymiana sprzęgła.' },
      { title: 'ZX1200i — drukarka przemysłowa nie komunikuje się przez Ethernet', description: 'Problem z modułem sieciowym lub konfiguracja IP. Reset sieci, diagnoza portu Ethernet, ewentualna wymiana modułu LAN.' },
    ],
    faqs: [
      { q: 'Ile kosztuje wymiana głowicy w Godex G500?', a: 'Wymiana głowicy w Godex G500/G530/RT700 od 430 PLN netto (serwis). Koszt głowicy 250–450 PLN netto (203 dpi) lub 400–650 PLN (300 dpi). Dla drukarek przemysłowych ZX/EZ6000 od 1 600 PLN netto.' },
      { q: 'Czy naprawiacie starsze modele Godex (G500 Plus, EZPi)?', a: 'Tak. Naprawiamy również starsze drukarki Godex — G500 Plus, EZPi-1200, EZPi-1300, DT4 (kompaktowe). Części do starszych modeli z większym czasem dostawy (7–10 dni), ale pełen zakres napraw jest realizowany.' },
      { q: 'Jak długo trwa naprawa Godex EZ2250i?', a: 'Diagnostyka w 48h od dostarczenia, naprawa 5–7 dni. Dla EZ2250i mamy głowice i wałki na stanie — większość napraw realizujemy w 5 dni. Dla rzadkich części (moduł BT, opcjonalny LCD) czas 7–10 dni.' },
      { q: 'Czy Godex używa oryginalnych chipów w głowicach?', a: 'Godex nie chipuje głowic — można używać głowic oryginalnych i kompatybilnych. TAKMA pracuje wyłącznie na oryginalnych głowicach Godex, co gwarantuje deklarowane parametry druku i żywotność 30 km (203 dpi) lub 20 km (300 dpi).' },
      { q: 'Dostarczacie części zamienne Godex dla serwisów?', a: 'Nie prowadzimy sprzedaży części B2B dla innych serwisów. Dostarczamy części i realizujemy kompleksową naprawę dla klienta końcowego.' },
    ],
  },
  {
    slug: 'sato',
    name: 'SATO',
    logoSrc: '/images/partners/logo_sato.png',
    logoAlt: 'Serwis drukarek etykiet SATO',
    category: 'drukarki',
    shortDesc: 'Drukarki CL4NX, CT4-LX, FX3-LX',
    products: 'Drukarki CL4NX, CT4-LX, FX3-LX',
    heroTitle: 'Serwis SATO — naprawa drukarek etykiet',
    heroDescription: 'Pogwarancyjny serwis drukarek SATO: CL4NX, CL6NX, CT4-LX, FX3-LX, WS408. Wymiana głowic, wałków, modułów LAN/Wi-Fi. Oryginalne części, wysyłka z całej Polski.',
    heroImage: '/images/serwis-hero/sato-hero.webp',
    heroLead: 'SATO to japoński producent zaawansowanych drukarek etykiet, obecny na polskim rynku od lat w produkcji, farmacji i logistyce. TAKMA serwisuje drukarki przemysłowe SATO z rodziny CL4NX, CL6NX (4" i 6" przemysłowe) oraz kompaktowe CT4-LX (linerless / z podkładem) i biurkowe FX3-LX, WS408. Wymieniamy głowice drukujące (kluczowe dla jakości druku GS1), wałki dociskowe, moduły LAN/Wi-Fi i obcinaki gilotynowe oraz prowadzimy pełną kalibrację.',
    metaTitle: 'Serwis SATO — naprawa drukarek CL4NX, CT4-LX, FX3-LX | TAKMA',
    metaDescription: 'Pogwarancyjny serwis drukarek SATO: CL4NX, CL6NX, CT4-LX, FX3-LX, WS408. Wymiana głowic, wałków. Darmowa diagnostyka — TAKMA Wrocław, cała Polska.',
    seriesList: [
      { series: 'CL4NX / CL6NX przemysłowe', description: 'Flagowe drukarki przemysłowe 4" (CL4NX) i 6" (CL6NX). Wytrzymała konstrukcja, kolorowy LCD, 203/305/609 dpi, do 356 mm/s. Do produkcji i magazynu.', typicalDevices: 'CL4NX, CL4NX Plus, CL6NX, CL6NX Plus' },
      { series: 'CT4-LX kompaktowe', description: 'Kompaktowe drukarki biurkowe CT4-LX, CT4-LX-HC (Healthcare). Wersje termiczne i termotransferowe, opcja linerless. Do apteczek i POS.', typicalDevices: 'CT4-LX, CT4-LX-HC, CT408i' },
      { series: 'FX3-LX / WS408', description: 'Kompaktowe biurkowe drukarki etykiet — FX3-LX, WS408. Wi-Fi, BT, Ethernet. Do małych wolumenów i farm.', typicalDevices: 'FX3-LX, WS408, WS412' },
      { series: 'Starsze przemysłowe', description: 'M84Pro, GL408e, GL412e — starsze modele przemysłowe wciąż używane w produkcji. Naprawiamy kompleksowo.', typicalDevices: 'M84Pro, GL408e, GL412e, LM408e' },
    ],
    commonIssues: [
      { title: 'CL4NX — białe pionowe linie na wydruku', description: 'Wypalone punkty na głowicy (thermal burnline damage). Wymiana głowicy 203/305/609 dpi — kluczowa operacja w CL4NX, wymaga kalibracji ciśnienia i temperatury.' },
      { title: 'CT4-LX — linerless drukuje krzywo / ślizga', description: 'Zużyty wałek dociskowy linerless (specjalny silikon antyadhezyjny) lub rozkalibrowana pozycja. Wymiana wałka + kalibracja.' },
      { title: 'CL6NX — drukarka "ciągnie" etykiety 6" nierównomiernie', description: 'Problem z prowadnicami nośnika lub napięciem sprężyn dociskowych w 6" mechanizmie. Regulacja + ewentualna wymiana prowadnic.' },
      { title: 'FX3-LX — "Head Open" mimo zamkniętej pokrywy', description: 'Czujnik pokrywy rozkalibrowany po upadku lub uszkodzona sprężyna blokady. Regulacja mechanizmu, wymiana czujnika.' },
      { title: 'CL4NX — obcinak gilotynowy nie tnie albo tnie krzywo', description: 'Zużyte ostrze gilotyny lub rozkalibrowany sterownik silnika. Wymiana ostrza + kalibracja, diagnostyka mechanizmu cięcia.' },
    ],
    faqs: [
      { q: 'Ile kosztuje wymiana głowicy w SATO CL4NX?', a: 'Wymiana głowicy w CL4NX/CL6NX od 1 600 PLN netto (serwis). Koszt samej głowicy 1 200–2 500 PLN netto zależnie od modelu i rozdzielczości (203/305/609 dpi). Dla FX3-LX/CT4-LX od 430 PLN netto (serwis).' },
      { q: 'Czy naprawiacie SATO CT4-LX w wersji linerless?', a: 'Tak. Wersja linerless CT4-LX wymaga specjalnego wałka antyadhezyjnego (różny od standardowego) oraz prowadnic bezpodkładowych. Mamy oryginalne części SATO dla wersji linerless, czas naprawy 5–7 dni.' },
      { q: 'Jak długo trwa naprawa SATO CL4NX?', a: 'Diagnostyka w 48h od dostarczenia, naprawa 5–7 dni. Dla CL4NX/CL6NX głowice 203 dpi i 305 dpi mamy na stanie; 609 dpi z dostawą 5 dni. Obcinaki gilotynowe — dostępne, 5 dni.' },
      { q: 'Czy TAKMA naprawia SATO M84Pro (starszy model)?', a: 'Tak, naprawiamy również starsze modele SATO (M84Pro, GL408e, GL412e, LM408e) wciąż używane w produkcji farmaceutycznej. Części do starszych modeli z dłuższym czasem dostawy (7–14 dni), ale pełen zakres napraw.' },
      { q: 'Dajecie gwarancję na naprawy SATO?', a: 'Tak — 3 miesiące na wymienioną głowicę drukującą, 3 miesiące na wałki i obcinaki, 6 miesięcy na naprawę płyty głównej/elektroniki. Warunki gwarancji omawiamy z klientem przed akceptacją kosztorysu, a zakres wykonanych prac opisujemy w protokole serwisowym.' },
    ],
  },
  {
    slug: 'tsc',
    name: 'TSC',
    logoSrc: '/images/partners/logo_tsc.png',
    logoAlt: 'Serwis drukarek etykiet TSC',
    category: 'drukarki',
    shortDesc: 'Drukarki TTP, TE, MH series',
    products: 'Drukarki TTP, TE, MH series',
    heroTitle: 'Serwis TSC — naprawa drukarek etykiet',
    heroDescription: 'Pogwarancyjny serwis drukarek TSC: TTP-225, TTP-244, TE200, TE310, MH241T, MH640T. Wymiana głowic, wałków, płyt głównych. Oryginalne części, cała Polska.',
    heroImage: '/images/serwis-hero/tsc-hero.webp',
    heroLead: 'TSC Auto ID Technology to jeden z najpopularniejszych producentów drukarek etykiet w Polsce — szczególnie w segmencie MSP i sklepów e-commerce. TAKMA serwisuje drukarki TSC z rodzin TTP (biurkowe: TTP-225, TTP-244 Pro, TTP-323), TE (kompaktowe: TE200, TE210, TE310), MH (przemysłowe: MH241T, MH341T, MH641T, MH640T), MB (rugged: MB240T, MB241T, MB340T) oraz ML (mobilne: ML240, ML340). Wymieniamy głowice drukujące, wałki dociskowe, płyty główne, moduły sieciowe i prowadzimy pełną kalibrację.',
    metaTitle: 'Serwis TSC — naprawa drukarek TTP, TE, MH series | TAKMA',
    metaDescription: 'Pogwarancyjny serwis drukarek TSC: TTP-225, TTP-244, TE200, TE310, MH241T, MH640T. Wymiana głowic, wałków, płyt głównych. TAKMA Wrocław.',
    seriesList: [
      { series: 'TTP Series', description: 'Biurkowe drukarki etykiet — TTP-225, TTP-244 Pro, TTP-245 Plus, TTP-323, TTP-323 Pro. Rozdzielczość 203/300 dpi, USB + Ethernet.', typicalDevices: 'TTP-225, TTP-244 Pro, TTP-245 Plus, TTP-323, TTP-323 Pro' },
      { series: 'TE Series', description: 'Kompaktowe biurkowe — TE200, TE210, TE310. Idealne do logistyki, e-commerce i małych sklepów.', typicalDevices: 'TE200, TE210, TE310, TE244' },
      { series: 'MH Series (przemysłowe)', description: 'Drukarki przemysłowe 4" i 6" — MH241T, MH341T, MH641T, MH640T, MH261T. Metalowa obudowa, praca 24/7.', typicalDevices: 'MH241T, MH341T, MH361T, MH641T, MH640T' },
      { series: 'MB Series rugged', description: 'Srebrne przemysłowe — MB240T, MB241T, MB340T. Alternatywa dla Zebry ZT w niższej cenie.', typicalDevices: 'MB240T, MB241T, MB340T, MB241T-A' },
      { series: 'ML Mobile Print', description: 'Mobilne drukarki etykiet — ML240, ML340. BT, bateria, do pola i serwisu.', typicalDevices: 'ML240, ML340, ML340P' },
    ],
    commonIssues: [
      { title: 'TTP-244 Pro / TE310 — białe paski na wydruku', description: 'Wypalone punkty głowicy. Wymiana głowicy 203 dpi lub 300 dpi (oryginalna TSC), kalibracja docisku i temperatury. Gwarancja 3 miesiące.' },
      { title: 'MH241T / MH341T — drukarka przemysłowa ma "Ribbon Out"', description: 'Rozkalibrowany czujnik taśmy lub zużyte sprzęgło nawijaka. Regulacja sensora, wymiana sprzęgła nawijaka taśmy.' },
      { title: 'TTP-225 — drukuje rozmazane etykiety', description: 'Zużyty wałek dociskowy (platen roller) lub niewłaściwa temperatura głowicy w sterowniku. Wymiana wałka + kalibracja profilu druku.' },
      { title: 'MH640T 6" — przesuwa etykiety krzywo', description: 'Problem z prowadnicami 6" nośnika lub czujnikiem przerw. Regulacja prowadnic + kalibracja czujnika.' },
      { title: 'TE200 — nie łączy się przez Ethernet / USB', description: 'Problem z modułem sieciowym lub portem USB. Diagnoza portów, reset konfiguracji, ewentualna wymiana modułu interfejsu.' },
    ],
    faqs: [
      { q: 'Ile kosztuje wymiana głowicy w TSC TTP-244?', a: 'Wymiana głowicy w biurkowych modelach TSC (TTP-244 Pro, TTP-245 Plus, TTP-323, TE310) od 430 PLN netto za sam serwis. Koszt oryginalnej głowicy TSC: ok. 280–420 PLN netto dla 203 dpi, 450–680 PLN dla 300 dpi (zależnie od modelu). W drukarkach przemysłowych MH241T / MH341T / MH641T serwis od 1 600 PLN netto, głowica od 900 PLN netto.' },
      { q: 'Czy naprawiacie drukarki TSC w wersji przemysłowej MH/MB?', a: 'Tak. Pełen zakres napraw drukarek przemysłowych TSC — MH241T, MH341T, MH361T, MH641T, MH640T, MB240T, MB340T. Wymiana głowic przemysłowych, mechanizmów nawijaka, silników krokowych, płyt głównych.' },
      { q: 'Jak długo trwa naprawa TSC TE310?', a: 'Diagnostyka w 48h od dostarczenia, naprawa 5 dni. Dla TE200/TE210/TE310 mamy na stanie kluczowe części (głowice, wałki). Większość napraw kompaktowych drukarek TSC realizujemy w 5 dni od dostarczenia.' },
      { q: 'Czy można regenerować głowice TSC?', a: 'Nie. Uszkodzone głowice termiczne (wypalone punkty) nie podlegają regeneracji — wymagają wymiany. Używamy wyłącznie oryginalnych głowic TSC, co gwarantuje deklarowaną żywotność 30 km druku (203 dpi) lub 20 km (300 dpi).' },
      { q: 'Dajecie gwarancję na naprawę TSC?', a: 'Tak — 3 miesiące na wymienioną głowicę, 3 miesiące na wałki dociskowe, 6 miesięcy na naprawę elektroniki. Do odsyłanej drukarki dołączamy specyfikację wymienionych części i numery seryjne wykorzystanych komponentów TSC.' },
    ],
  },
  {
    slug: 'brother',
    name: 'Brother',
    logoSrc: '/images/partners/brother_logo.png',
    logoAlt: 'Serwis drukarek etykiet Brother',
    category: 'drukarki',
    shortDesc: 'Drukarki mobilne RJ, TD, QL',
    products: 'Drukarki mobilne RJ, TD, QL',
    heroTitle: 'Serwis Brother — naprawa drukarek etykiet RJ, TD, QL',
    heroDescription: 'Pogwarancyjny serwis drukarek Brother: RJ-3050/RJ-4040 (mobilne), TD-2120N/TD-4550DNWB (biurkowe), QL-810W/QL-1110NWB (DK labels). Wymiana głowic, baterii, wałków.',
    heroImage: '/images/serwis-hero/brother-hero.webp',
    heroLead: 'Brother to japoński producent drukarek etykiet znany z trzech rodzin: QL (etykietarki z oryginalnymi etykietami DK), TD (biurkowe termiczne i termotransferowe) i RJ (mobilne do serwisu w terenie). TAKMA serwisuje drukarki Brother RJ (RJ-2050, RJ-3050, RJ-3150, RJ-4040), TD (TD-2120N, TD-2130N, TD-4420DN, TD-4550DNWB) oraz QL (QL-810W, QL-1100, QL-1110NWB). Wymieniamy głowice drukujące, baterie, wałki dociskowe, obcinaki i moduły Wi-Fi/Bluetooth.',
    metaTitle: 'Serwis Brother — naprawa drukarek RJ, TD, QL | TAKMA',
    metaDescription: 'Pogwarancyjny serwis drukarek Brother: RJ-3050, RJ-4040, TD-2120N, TD-4550DNWB, QL-810W, QL-1110NWB. Wymiana głowic, baterii — TAKMA Wrocław.',
    seriesList: [
      { series: 'RJ Series (mobilne)', description: 'Mobilne drukarki etykiet z baterią — RJ-2050, RJ-3050, RJ-3150, RJ-4030, RJ-4040. BT, Wi-Fi, ładowarki samochodowe. Do serwisu w polu, logistyki.', typicalDevices: 'RJ-2050, RJ-3050, RJ-3150, RJ-4030, RJ-4040' },
      { series: 'TD Series (biurkowe)', description: 'Biurkowe drukarki etykiet — TD-2120N, TD-2130N, TD-4420DN, TD-4550DNWB. Termiczne i termotransferowe, 203/300 dpi.', typicalDevices: 'TD-2120N, TD-2130N, TD-4420DN, TD-4520DN, TD-4550DNWB' },
      { series: 'QL Series (DK labels)', description: 'Etykietarki QL — QL-810W, QL-820NWB, QL-1100, QL-1110NWB. Współpracują z oryginalnymi etykietami DK Brother. Idealne do biura, magazynu i oznakowania przesyłek.', typicalDevices: 'QL-810W, QL-820NWB, QL-1100, QL-1110NWB, QL-600' },
      { series: 'PT Series (P-touch)', description: 'Etykietarki P-touch — PT-E550W, PT-P900W, PT-D800W. Do oznakowania przewodów, infrastruktury, archiwizacji.', typicalDevices: 'PT-E550W, PT-P900W, PT-D800W, PT-E800W' },
    ],
    commonIssues: [
      { title: 'RJ-3050/RJ-4040 — bateria wyczerpuje się w 30 minut', description: 'Bateria po 2–3 latach pracy traci pojemność. Wymiana baterii na oryginalną Brother (PA-BT-4000LI lub PA-BT-003) — pojemność wraca do deklarowanych wartości.' },
      { title: 'TD-2130N — białe pasy na etykietach', description: 'Wypalone punkty głowicy termicznej. Wymiana głowicy 203 lub 300 dpi. Używamy oryginalnych głowic Brother, gwarancja 3 miesiące.' },
      { title: 'QL-810W/QL-1110NWB — nie czyta rolki DK', description: 'Zabrudzony lub uszkodzony czujnik DK (optyczny). Czyszczenie okienka, kalibracja, ewentualna wymiana sensora.' },
      { title: 'RJ-3050 — nie łączy się z telefonem przez BT', description: 'Reset modułu BT, ewentualny firmware update. Jeśli moduł uszkodzony — wymiana płyty głównej (w RJ zintegrowana z radiem).' },
      { title: 'TD-4550DNWB — obcinak gilotynowy nie tnie', description: 'Zużyte ostrze gilotyny lub silnik obcinaka. Wymiana ostrza + diagnoza mechanizmu cięcia.' },
    ],
    faqs: [
      { q: 'Czy naprawiacie wszystkie drukarki Brother QL?', a: 'Tak. Pełen zakres napraw QL-810W, QL-820NWB, QL-1100, QL-1110NWB, QL-600. Najczęstsze usterki: wymiana czujnika DK, głowicy termicznej, zasilacza, modułu Wi-Fi.' },
      { q: 'Ile kosztuje wymiana baterii w Brother RJ-3050?', a: 'Wymiana baterii w drukarkach mobilnych RJ od 120 PLN netto (serwis). Koszt oryginalnej baterii Brother PA-BT-4000LI / PA-BT-003 — 250–400 PLN netto. Całkowicie od 370 PLN netto za kompletną wymianę.' },
      { q: 'Czy naprawiacie etykietarki Brother P-touch?', a: 'Tak. Serwisujemy również P-touch (PT-E550W, PT-P900W, PT-D800W). Najczęstsze problemy: brak detekcji rolki TZe, pęknięty ekran LCD, uszkodzony obcinak. Naprawa w 5–7 dni.' },
      { q: 'Jak długo trwa naprawa Brother TD-4550DNWB?', a: 'Diagnostyka w 48h od dostarczenia, naprawa zwykle 5 dni roboczych. Dla TD-2120N/TD-4420DN/TD-4550DNWB mamy kluczowe części na stanie. Dla starszych modeli czas dostawy 7–10 dni.' },
      { q: 'Dajecie gwarancję na naprawę Brother?', a: 'Tak — 3 miesiące na wymienioną głowicę, 3 miesiące na baterię i wałek dociskowy, 6 miesięcy na naprawę elektroniki. Szczegółowe warunki gwarancji przekazujemy w kosztorysie przed rozpoczęciem naprawy.' },
    ],
  },
]

export function getBrandBySlug(slug: string): ServiceBrand | undefined {
  return serviceBrands.find(b => b.slug === slug)
}

export function getAllBrandSlugs(): string[] {
  return serviceBrands.map(b => b.slug)
}
